import { ReactNode } from 'react';
import type { Metadata } from 'next';

import PageLayout from '@/components/common/layout/page-layout/PageLayout';
import Providers from '@/components/common/layout/providers';
import montserrat from '@/styles/fonts';

import '../styles/global.css';
import '../styles/reset.css';

export const metadata: Metadata = {
  title: 'Autolab',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="uk-UA">
      <body className={montserrat.className} style={{ height: '100vh' }}>
        <Providers>
          <PageLayout>{children}</PageLayout>
        </Providers>
      </body>
    </html>
  );
}
