import { ReactNode } from 'react';
import type { Metadata } from 'next';

import prompt from '@/styles/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Autolab',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="uk-UA">
      <body className={prompt.className}>{children}</body>
    </html>
  );
}
