import { ReactNode } from 'react';
import type { Metadata } from 'next';

import PageLayout from '@/components/common/layout/page-layout/PageLayout';
import prompt from '@/styles/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Autolab',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="uk-UA">
      <body className={prompt.className}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
